# Generated by Django 3.2.16 on 2024-12-02 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20241129_2019'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredientrecipe',
            options={'verbose_name': 'Ингредиент и Рецепт', 'verbose_name_plural': 'Ингредиенты и Рецепты'},
        ),
        migrations.AlterModelOptions(
            name='tagrecipe',
            options={'verbose_name': 'Тег и Рецепт', 'verbose_name_plural': 'Теги и Рецепты'},
        ),
        migrations.AlterUniqueTogether(
            name='ingredient',
            unique_together=set(),
        ),
    ]
