# Generated by Django 3.2.16 on 2024-12-02 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20241202_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='measurement_unit',
            field=models.CharField(help_text='Единицы измерения, не более 64 символов.', max_length=64, verbose_name='Единицы измерения'),
        ),
    ]
