# Generated by Django 3.2.16 on 2024-12-06 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_auto_20241205_1217'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subsrtictions',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='subsrtictions',
            name='author',
        ),
        migrations.RemoveField(
            model_name='subsrtictions',
            name='user',
        ),
    ]
