# Generated by Django 3.2.16 on 2024-12-06 07:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0008_auto_20241206_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='current_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL, verbose_name='Текущий пользователь'),
        ),
        migrations.DeleteModel(
            name='Subsrtictions',
        ),
    ]
