MAX_LENGTH_NAME = 256
MAX_LENGTH_NAME_INGREDIENT = 128
MAX_LENGTH_MEASURE_UNIT = 64
MAX_LENGTH_NAME_TAG = 32
MAX_LENGTH_SLUG = 32
MAX_LENGTH_SHORT_LINK = 5
MAX_LENGTH_EMAIL = 254
MAX_LENGTH_FOR_USER = 150

