# Generated by Django 3.2.16 on 2024-12-06 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodgramuser',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='foodgramuser',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Аватар пользователя, закодированный в Base64', null=True, upload_to='users/images/', verbose_name='Аватар пользователя'),
        ),
    ]
